AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AutoU Mail Triage API (FastAPI + Mangum)

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.11
    Architectures: [x86_64]

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "https://main.d3l1x3np6g7b9p.amplifyapp.com"
        AllowMethods:
          - GET
          - POST
          - OPTIONS

        AllowHeaders:
          - content-type
          - x-user-lang
          - accept-language

        AllowCredentials: false

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handler        
      CodeUri: .
      Environment:
        Variables:

          ALLOWED_ORIGINS: "https://main.d3l1x3np6g7b9p.amplifyapp.com,http://localhost:5173"
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: "Base URL da API"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"
